  # PG ADMIN
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSumus/62
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data
    ports:
      - "8080:80"



# Networks
networks:
  bank_app_network:
    external: true