x-common-environment:
  &common-env
  API_VERSION: 0.2.0
  API_STATE: TEST
  API_URL: http://bank_app_api:8000


services:
  # PostGres Container
  bank_app_postgres:
    image: postgres:14
    container_name: bank_app_postgres
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bank_app_network


  # API Container
  bank_app_api:
    image: personal_bank_app_api:test
    build:
      context: ../src/api
      dockerfile: Dockerfile_test
    container_name: bank_app_api
    env_file:
      - api.env
    environment:
      <<: *common-env
    volumes:
      - ../src/api:/app
    ports:
      - "8000:8000"
    depends_on:
      - bank_app_postgres
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 120s
      timeout: 10s
      retries: 3
    networks:
      - bank_app_network


  # Streamlit Container
  bank_app_streamlit:
    image: personal_bank_app_streamlit:test
    build:
      context: ../src/streamlit
      dockerfile: Dockerfile_test
    container_name: bank_app_streamlit
    environment:
      <<: *common-env
    volumes:
      - ../src/streamlit:/app
    ports:
      - "8001:8001"
    depends_on:
      - bank_app_api
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://container_api:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bank_app_network


  # Optional - PG Admin
  # container_pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=test@test.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - "5050:80"
  #   restart: always
  #   networks:
  #     - bank_app_network


# Networks
networks:
  bank_app_network:
    external: true