# API image
FROM postgres:13

# Copy files

COPY ./generate_tables.py .


# Install dependencies
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip install psycopg2

# Port to expose
EXPOSE 5432


# Define the entrypoint
ENTRYPOINT ["python3", "./generate_tables.py"]