# Version : 0.1.1
# Current state : Prod
# Author : Guillaume Pot
# Contact : guillaumepot.pro@outlook.com

services:
  # PostGres Container
  container_postgres:
    image: postgres:14
    container_name: bank_app_postgres
    env_file:
      - postgres.env
    volumes:
      - ../../storage/postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bank_app_network
# Networks
networks:
  bank_app_network:
    external: true