services:
  # PostGres Container
  container_postgres:
    image: postgres:13
    container_name: bank_app_postgres
    env_file:
      - postgres.env
    volumes:
      - ../../storage/postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bank_app_network
# Networks
networks:
  bank_app_network:
    external: true