# API image
FROM postgres:13

# Copy files

COPY ./generate_tables.py .


# Install dependencies
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv libpq-dev
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install psycopg2

# Port to expose
EXPOSE 5432


# Define the entrypoint
ENTRYPOINT ["python3", "./generate_tables.py"]