services:
  # PostGres Container
  container_postgres:
    image: postgres:14
    container_name: bank_app_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bank_db
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data
    # Comment ports if you don't want to access the database from the host
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bank_app_network


  # API Container
  container_api:
    image: personal_bank_app_api:test
    build:
      context: ../src/api
      dockerfile: Dockerfile
    container_name: bank_app_api
    environment:
      - POSTGRES_HOST=bank_app_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bank_db
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRATION=60
      - CRYPT_CONTEXT_SCHEME=argon2
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - API_VERSION=0.1.4
      - API_STATE=TEST
      - AUTHORIZED_USERS=root
    ports:
      - "8000:8000"
    depends_on:
      - container_postgres
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 120s
      timeout: 10s
      retries: 3
    networks:
      - bank_app_network


  # Streamlit Container
  container_streamlit:
    image: personal_bank_app_streamlit:test
    build:
      context: ../src/streamlit
      dockerfile: Dockerfile
    container_name: bank_app_streamlit
    environment:
      - API_VERSION=0.1.4
      - API_URL=http://bank_app_api:8000
    ports:
      - "8001:8001"
    depends_on:
      - container_api
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://container_api:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bank_app_network


  # Optional: PG Admin
  # container_pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=mail@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   ports:
  #     - "5050:80"
  #   restart: always
  #   networks:
  #     - bank_app_network


# Networks
networks:
  bank_app_network:
    external: true