# Streamlit Python image
ARG PYTHON_VERSION=3.10.12
FROM python:${PYTHON_VERSION}


# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

# Define Workdir
WORKDIR /app

# Copy files
COPY ./requirements.txt /app
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Port to expose
EXPOSE 8001

# Start streamlit server
CMD streamlit run streamlit.py --server.port 8001