# Streamlit Python image
ARG PYTHON_VERSION=3.10.12
FROM python:${PYTHON_VERSION}


# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1


# Define Workdir
WORKDIR /app

# Copy files
COPY ./requirements_streamlit.txt /app
COPY ./streamlit_main.py /app
COPY ./streamlit_api_requests_functions.py /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements_streamlit.txt

# Port to expose
EXPOSE 8001

# Start streamlit server
CMD streamlit run streamlit_main.py --server.port 8001

# Metadatas to the image
LABEL version="0.2.0"
LABEL description="Streamlit image v0.2.0, latest"