# Version : 0.1.0
# Current state : Dev
# Author : Guillaume Pot
# Contact : guillaumepot.pro@outlook.com


# Name of the workflow 
name : Upload Docker images

# Trigger
on:
  merge_request:
    branches: ["main"]


# Permissions accorded to the workflow
permissions:
  # Repo content
  contents: read
  # Secrets
  secrets: read
  

# Jobs
jobs:
  # Job - Push Streamlit image
  Push and push Streamlit image:
    runs-on: ubuntu-latest

    # Actions to execute
    steps:
      # Used to clone the repository in the runner
      - uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build & Push Docker Image
      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src/streamlit
          file: ./src/streamlit/Dockerfile
          push: true
          tags: Unclad3610/personal_bank_app_streamlit:latest

  # Job - Push FastAPI image
  Push and push FastAPI image:
    runs-on: ubuntu-latest

    # Actions to execute
    steps:
      # Used to clone the repository in the runner
      - uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build & Push Docker Image
      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src/api
          file: ./src/api/Dockerfile
          push: true
          tags: Unclad3610/personal_bank_app_api:latest